-- Users (Staff)
create table users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text check (role in ('admin', 'doctor', 'reception')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Patients
create table patients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  dob text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Appointments
create table appointments (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) not null,
  datetime text not null,
  reason text,
  status text default 'scheduled',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Clinical Notes
create table notes (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) not null,
  note text not null,
  created_by text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Invoices
create table invoices (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) not null,
  amount float not null,
  status text check (status in ('unpaid', 'paid', 'partial')) not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Treatment Plans
create table treatment_plans (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) not null,
  diagnosis text not null,
  plan text not null,
  estimated_cost float default 0,
  status text default 'proposed',
  created_by text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Prescriptions
create table prescriptions (
  id bigint generated by default as identity primary key,
  patient_id bigint references patients(id) not null,
  medication text not null,
  dosage text not null,
  frequency text not null,
  duration text not null,
  instructions text,
  prescribed_by text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Security)
alter table users enable row level security;
alter table patients enable row level security;
alter table appointments enable row level security;
alter table notes enable row level security;
alter table invoices enable row level security;
alter table treatment_plans enable row level security;
alter table prescriptions enable row level security;

-- Open Access Policies (Since we handle auth in the Node.js backend with Service Role/Anon)
-- In a real prod app, you'd lock this down further, but for this architecture:
create policy "Public Access" on users for all using (true) with check (true);
create policy "Public Access" on patients for all using (true) with check (true);
create policy "Public Access" on appointments for all using (true) with check (true);
create policy "Public Access" on notes for all using (true) with check (true);
create policy "Public Access" on invoices for all using (true) with check (true);
create policy "Public Access" on treatment_plans for all using (true) with check (true);
create policy "Public Access" on prescriptions for all using (true) with check (true);

-- Insert Default Admin User (Password: Admin@123)
insert into users (username, password_hash, role)
values ('admin', '$2a$10$M1yPS5RYTKIjNlOF1oLOOe4aMvh9lSbBPdjjMIM5KDHVITcptNuXW', 'admin');
