const { Client } = require('pg');

export default async function handler(req, res) {
  // Try the Pooler again. 
  // Assuming 'ap-south-1' (Mumbai) based on your location/previous attempts.
  // If this fails, we are stuck without manual intervention.
  const connectionString = 'postgres://postgres.ukabjwrlpnxaybrawxbc:%2Fw3qdnN%3F%2BqXFADF@aws-0-ap-south-1.pooler.supabase.com:6543/postgres';

  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    
    await client.query(`
      CREATE TABLE IF NOT EXISTS simulations (
        id bigint generated by default as identity primary key,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null,
        name text,
        mesh_data jsonb,
        stress_max float
      );
    `);

    await client.query('ALTER TABLE simulations ENABLE ROW LEVEL SECURITY;');

    await client.query(`
      DO $$ 
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'simulations' AND policyname = 'Enable read access for all users') THEN
          CREATE POLICY "Enable read access for all users" ON "public"."simulations" FOR SELECT USING (true);
        END IF;
        
        IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'simulations' AND policyname = 'Enable insert for all users') THEN
          CREATE POLICY "Enable insert for all users" ON "public"."simulations" FOR INSERT WITH CHECK (true);
        END IF;
      END $$;
    `);

    await client.end();
    res.status(200).json({ status: 'Success', message: 'Table created via Pooler.' });
    
  } catch (error) {
    console.error(error);
    res.status(500).json({ status: 'Error', error: error.message, stack: error.stack });
  }
}
